.travis.yml
Depends on https://github.com/aodn/utilities/pull/45
=> Add get_latest_artifact.py script

.gitignore, setup.py
... so that it can be printed in pipeline logs.
=> Add module version to entry points

aodndata/moorings/handlers.py, test_aodndata/moorings/test_abosHandler.py, test_aodndata/moorings/test_mooringsHandler.py
Requires https://github.com/aodn/harvesters/pull/615 and https://github.com/aodn/chef-private/pull/2889
=> MooringsHandler and AbosHandler to harvest non-netcdf files

aodndata/anfog/handlers.py, test_aodndata/anfog/test_anfog.py
- uncomment checks on nraw data in unittest
- set check type for file to be deleted
=> GLIDER pipeline update:

.coveragerc, .travis.yml, README.md
Add coverage/codecov to .travis.yml
=> Add codecov to .travis.yml

aodndata/gsla/handler.py, aodndata/srs/srs_ghrsst.py, aodndata/srs/srs_oc_gridded.py, test_aodndata/srs/test_srs_oc_gridded.py
Some changes were recently made in aodncore that require updates in aodndata (see https://github.com/aodn/python-aodncore/pull/117, https://github.com/aodn/python-aodncore/pull/120, https://github.com/aodn/python-aodncore/pull/121).
=> Updates to work with aodncore >= 0.19.1

aodndata/srs/srs_surface_waves.py, setup.py, test_aodndata/srs/test_srs_surface_waves.py
@ggalibert 
see my email re no time value in filename.
you can create the harvester when you want
=> Add handler for SRS Surface Waves

aodndata/srs/srs_surface_waves.py, test_aodndata/srs/test_srs_surface_waves.py
just as a heads up, 20*20 will still have a lot of files per folder
=> SRS SURFACE WAVES - requested changes to create bins of 20deg

aodndata/soop/soop_xbt_dm.py
@lwgordonimos don't know if that would be enough, or if this was the cause of the memory leak issue. But this works
=> SOOP XBT DM - memory leak fix attempt

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_abosFileClassifier.py
@mhidas , please check if this is what you expected to be done. I followed the pipeline v1 tests/code.
=> Pipeline v2 for abos waves sp sf

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_mooringsFileClassifier.py
Fixes https://github.com/aodn/content/issues/272
=> Update MooringsFileClassifier to classify ECO-PARSB and ECO-BB2FLWB

constraints.txt
~~this add required libs to the docker image, so both travis and jenkins can bootstrap the python-netcdf4 dependency  py3.5) for the tests.~~
see commit msg
=> feat(bugfix): include req. sys libs for netcdf4

aodndata/aatams/aatams_sattag.py, test_aodndata/aatams/test_aatams_sattag.py
This set an upload flag for the aatams dm/nrt zip files instead
of harvest and archive.
=> feat(bugfix): aatams zip file flag adjustments

aodndata/soop/soop_co2.py
=> fix range of valid day number

aodndata/moorings/classifiers.py, aodndata/moorings/handlers.py, test_aodndata/moorings/test_dwmFileClassifier.py, test_aodndata/moorings/test_dwmHandler.py
@mhidas I did changes in the moorings handler and test_dwmHandler. The tests ran alright, but you might find some non-sense coding. Anyway, it is a starting for discussion and it is working, which is a good sign! This is part of [issue#755](https://github.com/aodn/PO-Backlog/issues/755)
=> update DWM/SOTS pipeline to include calibration zip files

Dockerfile
Updated Dockerfile to use pyenv instead.
=> use pyenv for docker build env

constraints.txt
@mhidas this should fix this issue: https://github.com/aodn/content/issues/496
`testfixtures` module is installed in `setup.py` so I didn't update `constraints.txt`
=> update required version of testfixtures

Dockerfile
- update python version
- remove unnecessary python 3.5 condition
- update pyenv pre-requisites
=> various updates to Dockerfile including:

aodndata/soop/soop_co2_nrt_nc_generator.py, aodndata/templates/soop_co2_nrt_nc_template.json
=> Soop_co2_rt: upd ATMP variable name

aodndata/aims/mmp_ctd.py, setup.py, test_aodndata/aims/test_mmp_ctd.py
@mhidas this should be now good to test in RC
=> update aims mmp data to use generic handler

aodndata/moorings/moorings_product_trigger.py
A script to look at the currently published moorings (ANMN) source files and products files, determine which products need reprocessing, and generate the relevant manifest files to feed into the `MOORINGS_PRODUCTS` pipeline.
=> Moorings products processing trigger script

aodndata/aatams/aatams_acoustic_index_tmp.py
harvesting an extra field allowing an extra filter on portal
associated PRs:
- geoserver: https://github.com/aodn/geoserver-config/pull/783
- public schema: https://github.com/aodn/public-schema/pull/74
=> at_acoustic_qc harvest new field for new filter

aodndata/aodn_wave/handler.py, test_aodndata/aodn_wave/test_aodn_wave.py
Reverts aodn/python-aodndata#362
=> Revert "fix imos wave dirs"

aodndata/aodn_wave/handler.py
Reverts aodn/python-aodndata#369
=> Revert "add flinders to wave handler"

aodndata/aodn_wave/handler.py
Reverts aodn/python-aodndata#374
=> Revert "Revert "add flinders to wave handler""

aodndata/aatams/aatams_sattag_schema.py
Should address recent ingestion issue in /mnt/ebs/log/pipeline/process/tasks.AATAMS_SATTAG_QC_DM.log
=> Modify aatams_sattag_schema to ingest turtle data

scripts/setup_virtualenv.sh
https://github.com/aodn/issues/issues/1502
=> lock pip version to support non-standard dependency specifier

aodndata/aatams/aatams_sattag_schema.py
Reverts aodn/python-aodndata#393
Checking if tests fail
=> Revert "Add code in aatams_sattag_schema for GPS table"
