aodn/python-aodndata

.gitignore, README.md, setup_virtualenv.sh
This script shortcuts the setup of a virtual environment containing the package dependencies. The idea being that you can just checkout python-aodndata, run the script and have it setup and ready to develop in (e.g. from PyCharm). Could be tided up in future in a few ways, but does the job for now (assuming boto3 and wget are installed).
```bash
$ git clone git@github.com:aodn/python-aodndata.git && cd python-aodndata
$ ./setup_virtualenv.sh 
Downloading dependencies...
Creating virtual environment...
Installing dependencies into virtual environment...
Virtual environment successfully created at: python-aodndata-virtualenv
To use:
* Configure PyCharm project interpreter as: /tmp/python-aodndata/python-aodndata-virtualenv/bin/python
* Activate in shell environment: $ source …
```
=> Developer documentation and dev environment setup

aodndata/moorings/handlers.py, test_aodndata/moorings/test_mooringsHandler.py
This PR doesn't change the behaviour of the MooringsHandler, its just to "modernise" the code to make use of new helper methods that were introduced after the handler was created. The ABOS handler will be a subclass of this one, so I'd like to get this in before that one.
=> MooringsHandler: code clean up and update

aodndata/common/generic.py, aodndata/moorings/handlers.py, requirements.txt, test_aodndata/common/test_genericHandler.py
This is to account for the new default publish_type introduced by https://github.com/aodn/python-aodncore/pull/91
=> Update GenericHandler and MooringsHandler to work with aodncore 0.12

setup.py
This is for discussion as much as anything. I think it makes more sense to have the plugin dependency here rather than aodncore. 
`aodncore` certainly needs the base compliance checker because it is imported directly, but there's no point in testing anything to do with the additional check suites in core. The dependencies really belong to the specific handlers and/or pipelines, which are all defined here.
If defined here, we can then remove the dependency from aodncore for fewer moving parts during environment setup for unit testing etc.
=> Add cc-plugin-imos dependency (in order to remove from aodncore)

.travis.yml
This is an attempt to deal with cases where we're starting to use new aodncore functionality that hasn't been deployed to prod yet.
=> Use Travis build matrix to test against different versions of aodncore

aodndata/moorings/handlers.py, test_aodndata/moorings/test_abosHandler.py
This is to prevent a confusing exception ending up in the notify email if the file name doesn't match the expected pattern.
=> AbosHandler check for images zip file name pattern

.travis.yml
We want to test against the same pipeline stage (build/systest/prod) for all three artefacts aodndata is dependent on (aodncore, cc-plugin, ncwriter).
=> Update Travis test matrix 

aodndata/moorings/products_handler.py, setup.py, test_aodndata/moorings/test_mooringsProductsHandler.py
Add more useful metadata to the aggregated timeseries products generated, using the additional arguments introduced in https://github.com/aodn/python-aodntools/pull/78
(Also a bit of code clean-up.)
=> Moorings products: add download/opendap URL details

test_aodndata/nsw_oeh/test_nsw_oeh_handler.py
This amends https://github.com/aodn/python-aodndata/pull/161 to still build until https://github.com/aodn/python-aodndata/pull/180 is merged.
=> Update NswOehHandler tests to use six.assertCountEqual

aodndata/aatams/aatams_sattag.py
Fix a bug when we assumed the s3-storage
state was only containing zip files.
@evacougnon
=> feat(aatams): only select remote NRT zips on s3

aodndata/aatams/aatams_sattag.py, aodndata/soop/soop_trv.py, test_aodndata/soop/test_soop_trv.py
Found a couple of uses of deprecated methods, which would be good to correct while doing API refactoring.
=> Query wfs urls for layer deprecated

aodndata/soop/soop_xbt_nrt.py, aodndata/templates/soop_xbt_nrt_bufr_nc_template.json, test_aodndata/soop/test_soop_xbt_nrt.py
NetCDF files were created with IODE flags. Bec Cowley noticed that the flags were actually GTSPPE flags. These flags aren't part of the IMOS convention, so the NetCDF file aren't compliant anymore. This needs to be reflected in the chef-private databags
=> XBT NRT - QC falgs are GTSPPE (not IODE) -> not IMOS compliant anymore

aodndata/gsla/handler.py, test_aodndata/gsla/test_gsla.py
Add logic to transform a received NetCDF file into a .nc.gz
historically, files were always sent as *.nc.gz. But as of April 2021, files might be pushed as *.nc
To be consistent with the existing dataset, and gogoduck, we transform this .nc into a .nz.gz
=> GSLA - update handler to handle non gzipped files

.github/workflows/test.yml, constraints.txt
Update the GitHub Actions config to test against the most relevant versions of python, in line with python-aodncore.
=> Update GitHub Actions to test against python 3.8

stage_environment.yml
A conda environment file to simply deploy a working virtual environment. This is based on https://github.com/aodn/python-aodndata/blob/master/scripts/setup_virtualenv.sh
I have had issues with the original script with new version of ubuntu/mint. The old setup_virtualenv.sh script is using the system python to create a virtualenv. On the other end, this conda environment file doesn't rely on this. I would be happy to modify the README of this repo to add an alternative way to PO (like me), who have had issues with the virtualenv script, to setup a working python virtual env.
This doesn't need to be packaged in the wheel, and doesn't affect the repo apart from having a new file. I'm not too fussed if this is not added but I think it would be valuable.
FYI @ana-berger @mhidas @bpasquer …
=> Add conda stage_environmnent.yml file for PO dev

.github/workflows/test.yml
This should allow unittests to run successfully in both Python 3.5 and 3.8 (see https://github.com/aodn/python-aodncore/pull/235)
=> Don't pin numpy version in github actions

stage_environment.yml
see for ref https://stackoverflow.com/questions/68571543/using-a-pip-requirements-file-in-a-conda-yml-file-throws-attributeerror-fileno
=> (BugFix) New pip version 21.2.1 breaks conda env

.github/workflows/test.yml
This should allow all jobs in the matrix to run to the end (i.e., even when some fail) to give us more complete information.
=> Turn off fail-fast in github actions

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_dwmFileClassifier.py
Update pipeline to ingest hourly gridded products from CSIRO, as per https://github.com/aodn/PO-Backlog/issues/2277
=> modify DWM classifier and test for CSIRO gridded product

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_dwmFileClassifier.py
Recently updoaded FV00 ADCP files from the DWM-DA subfacility do not contain any of the common velocity variable names (`UCUR`, `VCUR`, etc...) used by the classifier to identify them as a "Velocity" product. Instead they end up being classified as "Temperature", which is incorrect.
The new files have velocity variables like
`VEL1:long_name = "sea_water_velocity_from_acoustic_beam_1"`
See https://github.com/aodn/PO-Backlog/issues/2392
=> Update MooringsFileClassifier to handle single-ping ADCP files from DWM facility

aodndata/imos_bgc_db/handler.py
Update the dest_path for CSV files harvested from CSIRO Geoserver to more clearly describe what they are (i.e. not to be confused with the data products we generate and make available via AODN Geoserver and Portal)
=> ImosBgcDbHandler: make dest_path more explicit

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_dwmFileClassifier.py
updated DWM classifier to also work for "hourly-depth-gridded-product": https://github.com/aodn/PO-Backlog/issues/2589
=> feat: allow hourly-depth-gridded-product in MooringsFileClassifier

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_mooringsFileClassifier.py
@mhidas I believe the check fails are related to the issues that you are already fixing for mooring products? Here is the error I get in my local machine when I run the `test_mooringsProductsHandler.py`:
> FAILED [ 41%]
test_aodndata/moorings/test_mooringsProductsHandler.py:130 (TestMooringsProductsHandler.test_velocity_hourly)
self = <test_aodndata.moorings.test_mooringsProductsHandler.TestMooringsProductsHandler testMethod=test_velocity_hourly>
=> Updating mooring pipeline to ingest NTP profiling mooring files

setup.py
Another version import change that was missed in previous PRs.
This one is needed so that the pipelines can report all the current package versions in their log. E.g.
```
... running handler -> MooringsHandler({'versions': {'python': '3.8.13', 'aodncore': '1.3.11', 'aodndata': '1.3.87', '
aodntools': '1.5.3', 'cc-plugin-imos': '1.4.11', 'compliance-checker': '4.1.1'}, ... )
```
Currently it is saying `'aodndata': 'LOAD_FAILED'`
=> fix aodndata module version entry point for aodncore

.github/workflows/test.yml, constraints.txt, setup.py
Numpy version 1.24 has removed types `numpy.int` and `numpy.float`, which are referenced in current versions of the compliance-checker (and our plugin). We need to avoid this version of numpy until those packages have been updated accordingly.
Same issue as https://github.com/aodn/python-aodncore/pull/272
=> Constrain numpy version to fix unittests

aodndata/aims/mmp_ctd.py, test_aodndata/aims/test_mmp_ctd.py
Roxana realised that does not want the `site_short_name` in the final folder structure..
Thus, new agreed structure is `AIMS/Marine_Monitoring_Program/CTD_profiles/YYYY/*.nc`
=> MMP update destination path

aodndata/moorings/moorings_product_trigger.py
This is just a small fix to allow the `moorings_product_trigger.py` script to process all sites by default (when no sub-facility or sites are specified on the command-line).
=> moorings_product_trigger fixup: process all sites

aodndata/aatams/aatams_acoustic.py
just a little tweak as some transmitter IDs have shorter ID code (last section of the transmitter ID) than I expected
=> feat: animal tracking acoustic regex tagID

aodndata/moorings/classifiers.py, test_aodndata/moorings/test_dwmFileClassifier.py
@mhidas 
I could not use `_get_nc_att` because it was failing some unittest. Indeed, it was raising an `InvalidFileContentError` (you can have a look at my first attempt in commit 435d59c) for the files that do not have 'data_product_type' as attribute. I then avoid using '_get_nc_att' and used instead `_open_nc_file` and `hasattr` to avoid the `InvalidFileContentError` (commit ade1b3f)
=> Publish SOTS gridded multiyear data in new sub-directory

aodndata/aatams/aatams_sattag_schema.py
After testing changes made in https://github.com/aodn/python-aodndata/pull/389, further modification of the schema has been deemed necessary as the turtle files couldn't get ingested by the pipeline on rc.
=> Further modif to aatams_sattag_schema

.github/workflows/test.yml
https://github.com/aodn/issues/issues/1498
=> lock pip version to use the required click module version

.github/workflows/test.yml, constraints.txt
We have had issues with the unit tests failing for the following PRs:
- https://github.com/aodn/PO-Backlog/issues/3980
- https://github.com/aodn/PO-Backlog/issues/3935
- https://github.com/aodn/backlog/issues/6473
**Error**
The error ([see issue here](https://github.com/aodn/issues/issues/1544)) was due to the `pytz>dev` requirement that `celery==5.1.2` had, which is a [known issue](https://github.com/celery/celery/discussions/9112).
**Cause**
It is a known bug in `celery==5.1.2` that it incorrectly specifies the invalid requirement `pytz>dev`. This is allowed when using `pip==24.0` (as in our case), but if we upgraded pip it would fail.
We can't upgrade celery, because we require `fiona==1.8.18` (as per this requirement `fiona>=1.8.8,<1.8.19` in aodncore) that requires `click<=7.1.2`. …
=> Fix-unittests
